version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: nuget restore Zilon.Core/Zilon.Game.sln
      - run: msbuild Zilon.Core/Zilon.Game.sln /t:Build /p:Configuration=Release
  test_45:
    working_directory: /test45
    docker:
      - image: mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      ZILON_LIV_SCHEME_CATALOG: ./Zilon.Client/Assets/Resources/Schemes
    steps:
      - checkout
      - run: nuget restore Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj -SolutionDirectory ./Zilon.Core
      - run: msbuild Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj /p:Configuration=Release
      - run: mono --debug /test45/Zilon.Core/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe Zilon.Core/Zilon.Core.Tests/bin/Release/Zilon.Core.Tests.dll --encoding utf-8
  build_Win_x64:
    docker:
      - image: gableroux/unity3d:latest
    steps:
      - checkout
      - run:
        environment:
          BUILD_TARGET: StandaloneWindows64
        command: "./ci/build.sh"
    - store_artifacts:
        path: "./Builds/"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_45
      - build_Win_x64