version: 2
jobs:
  build:
    docker:
      - image: aparker/circleci-dotnet-mono:latest
    steps:
      - checkout
      - run: nuget restore Zilon.Core/Zilon.Game.sln
      - run: msbuild Zilon.Core/Zilon.Game.sln /t:Build