version: 2
jobs:
  build:
    working_directory: /core-builds
    docker:
      - image: mono:latest
    steps:
      - checkout
      - run: nuget restore Zilon.Core/Zilon.Core/Zilon.Core.csproj -SolutionDirectory ./Zilon.Core
      - run: nuget restore Zilon.Core/Zilon.Bot.Players/Zilon.Bot.Players.csproj -SolutionDirectory ./Zilon.Core
      - run: msbuild Zilon.Core/Zilon.Core/Zilon.Core.csproj /t:Build /p:Configuration=Release /p:OutputPath=../../bin
      - run: msbuild Zilon.Core/Zilon.Bot.Players/Zilon.Bot.Players.csproj /t:Build /p:Configuration=Release /p:OutputPath=../../bin
      - persist_to_workspace:
          root: bin
          paths:
            - ./*
  test_45:
    working_directory: /test45
    docker:
      - image: mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      ZILON_LIV_SCHEME_CATALOG: ./Zilon.Client/Assets/Resources/Schemes
    steps:
      - checkout
      - run: nuget restore Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj -SolutionDirectory ./Zilon.Core
      - run: msbuild Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj /p:Configuration=Release
      - run: mono --debug /test45/Zilon.Core/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe Zilon.Core/Zilon.Core.Tests/bin/Release/Zilon.Core.Tests.dll --encoding utf-8
  build_Win_x64:
    docker:
      - image: gableroux/unity3d:2019.2.5f1-windows
    steps:
      - checkout
      - run: mkdir -p /root/.cache/unity3d
      - run: mkdir -p /root/.local/share/unity3d/Unity/
      - run: openssl aes-256-cbc -d -in .circleci/Unity_v2019.x.ulf-cipher -k ${CIPHER_KEY} >> /root/.local/share/unity3d/Unity/Unity_lic.ulf
      - attach_workspace:
          at: /core-builds/bin
      - run: mkdir -p ./Zilon.Client/Assets/Plugins/ && cp -a /core-builds/bin/. ./Zilon.Client/Assets/Plugins/
      - run:
          command: |
            apt update && apt install -y git 
            git clone https://github.com/kreghek/Zilon_Roguelike_Plugins.git temp
      - run: cp -a temp/. ./Zilon.Client/Assets/Plugins/
      - run:
          name: Build
          command: chmod +x .circleci/build.sh && .circleci/build.sh
      - run:
          name: Zipping build
          command: apt update && apt -y install zip && zip -r LAST.zip ./Zilon.Client/Builds/*
      - store_artifacts:
          path: LAST.zip
  
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - circle-ci
                - /release-.*/
      - test_45:
          filters:
            branches:
              only:
                - master
                - circle-ci
                - /release-*/
      - build_Win_x64:
          filters:
            branches:
              only:
                - master
                - circle-ci
                - /release-.*/
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - build
      - build_Win_x64:
          requires:
            - build