name: Benchmarks

on: push

jobs:
  buildCore:
    name: Run benchs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench_project:
          - Zilon.Core.Benchmarks.Move
        include:
          - bench_project: Zilon.Core.Benchmarks.Move
          - bench_filter: GamePlayBench
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Runc Dotnetenchmark ${{ matrix.bench_project }}
        env:
          ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OUTPUT: 1
        run: dotnet run --project Zilon.Core/${{ matrix.bench_project }}/${{ matrix.bench_project }}.csproj --configuration Release --filter *${{ matrix.bench_filter }}*