name: Benchmarks

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  buildCore:
    name: Run benchs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bench_project:
          - Zilon.Core.Benchmarks.Gameplay
          - Zilon.Core.Benchmarks.Fow
          - Zilon.Core.Benchmarks.CreateSector
          - Zilon.Core.Benchmarks.MassGameplay
        include:
          - bench_project: Zilon.Core.Benchmarks.Gameplay
            bench_filter: GamePlayBench
          - bench_project: Zilon.Core.Benchmarks.Fow
            bench_filter: FowDataBench
          - bench_project: Zilon.Core.Benchmarks.CreateSector
            bench_filter: CreateCellularAutomatonSectorBench
          - bench_project: Zilon.Core.Benchmarks.MassGameplay
            bench_filter: MassGamePlayBench
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run DotNetBenchmark ${{ matrix.bench_project }}
        env:
          ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OUTPUT: 1
        run: dotnet run --project Zilon.Core/${{ matrix.bench_project }}/${{ matrix.bench_project }}.csproj --configuration Release --filter *${{ matrix.bench_filter }}*
      - uses: actions/upload-artifact@v3
        with:
          name: benchs
          path: BenchmarkDotNet.Artifacts/results