name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  WORKING_DIRECTORY: CDT.LIV.Game

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    strategy:
      matrix:
        project:
          - Zilon.TextClient
        configuration:
          - Release
        runtime:
          - win10-x64
          - ubuntu.16.10-x64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup .NET5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - run: ls /home/runner/work/CDT.LIV.MonoGameClient/CDT.LIV.MonoGameClient/Zilon.Core/Zilon.Client/Assets/Resources/Schemes/
      - name: Copy schemes
        run: cp -R /home/runner/work/CDT.LIV.MonoGameClient/CDT.LIV.MonoGameClient/Zilon.Core/Zilon.Client/Assets/Resources/Schemes/*.json /home/runner/work/CDT.LIV.MonoGameClient/CDT.LIV.MonoGameClient/CDT.LIV.Game/CDT.LIV.MonoGameClient/bin/Release/net5/Content/Schemes/
        
      - name: Publish
        run: dotnet publish --configuration ${{ matrix.configuration }} --framework net5 --output bin --runtime ${{ matrix.runtime }}
        
      - name: Upload client into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: LIV.Game
          path: bin