name: Build game clients

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build clients in Release mode
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - Zilon.TextClient
          - CDT.LAST.MonoGameClient
        configuration:
          - Release
          - Debug
        runtime:
          - win-x64
          - linux-x64
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Publish ${{ matrix.project }} ${{ matrix.configuration }} ${{ matrix.runtime }}
        if: ${{ contains('Release', matrix.configuration) }}
        run: dotnet publish Zilon.Core/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration ${{ matrix.configuration }} --framework net5 --output bin --runtime ${{ matrix.runtime }} --self-contained true /p:DebugType=None /p:DebugSymbols=false /p:PublishSingleFile=true

      - name: Publish ${{ matrix.project }} ${{ matrix.configuration }} ${{ matrix.runtime }}
        if: ${{ contains('Debug', matrix.configuration) }}
        run: dotnet publish Zilon.Core/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration ${{ matrix.configuration }} --framework netcoreapp3.1 --output bin --runtime ${{ matrix.runtime }} --no-self-contained

      - name: Copy scheme catalog into bin directory for ${{ matrix.project }}
        if: ${{ contains('MonoGameClient', matrix.project) }}
        run: cp -a /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Core/Zilon.Client/Assets/Resources/Schemes/. /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/CDT.LIV.Game/bin/Content/Schemes/
      
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.project }}-Release
          path: bin