name: Coverall report Core Unit Tests

on:
  pull_request:
    branches:
      - master
    tags:
      - 'v*.*.*'
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Generate coverage report
      env:
        ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OUTPUT: 1
      run: |
        cd ./Zilon.Core/Zilon.Core.Tests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/ /p:CoverletOutputFormat=lcov
        cd ./Zilon.Core/Zilon.Bot.Players.Tests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/ /p:CoverletOutputFormat=lcov /p:MergeWith=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/coverage.info
        cd ./Zilon.Core/Zilon.Core.Specs/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/ /p:CoverletOutputFormat=lcov /p:MergeWith=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/coverage.info
        cd ./Zilon.Core/Zilon.Core.DiTests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/ /p:CoverletOutputFormat=lcov /p:MergeWith=/home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/coverage.info
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/coverage.info