name: Coverall report Core Unit Tests

on:
  pull_request:
    branches:
      - master
    tags:
      - 'v*.*.*'
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

env:
  TEST_RESULT_PATH: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Generate coverage report
      env:
        ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OUTPUT: 1
      run: |
        cd ./Zilon.Core
        dotnet test Zilon.Core.Tests/Zilon.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=lcov
        dotnet test Zilon.Bot.Players.Tests/Zilon.Bot.Players.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=lcov /p:MergeWith=${{env.TEST_RESULT_PATH}}coverage.info
        dotnet test Zilon.Core.Specs/Zilon.Core.Specs.csproj /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=lcov /p:MergeWith=${{env.TEST_RESULT_PATH}}coverage.info
        dotnet test Zilon.Core.DiTests/Zilon.Core.DiTests.csproj /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=lcov /p:MergeWith=${{env.TEST_RESULT_PATH}}coverage.info
        dotnet test Zilon.Bot.Players.DevelopmentTests/Zilon.Bot.Players.DevelopmentTests.csproj /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=lcov /p:MergeWith=${{env.TEST_RESULT_PATH}}coverage.info
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/coverage.info