name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release-candidat
      - drafter

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

