name: SonarCloud

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@v2.1.1-beta
        with:
          # The key of the SonarQube project
          sonarProjectKey: kreghek_Zilon_Roguelike
          # The name of the SonarQube project
          sonarProjectName:  Zilon Roguelike
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: kreghek
          dotnetBuildArguments: Zilon.Core/Zilon.Core.SonarScanner.sln -c Release
          dotnetDisableTests: true