name: SonarCloud

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - '!dependabot/nuget/**'
  pull_request:
    branches:
      - master
      - '!dependabot/nuget/**'
    types:
      - opened
      - synchronize
      - reopened

env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      working-directory : $GITHUB_WORKSPACE
    steps:
      - uses: actions/checkout@v2

      - name: Setup ReSharper Command Line Tools
        run: dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2021.1.2

      - name: Inspect codebase via ReSharper Command Line Tools
        # use --absolute_paths to fix a issues https://github.com/olsh/dotnet-reqube/issues/9 + https://youtrack.jetbrains.com/issue/RSRP-484145
        run: jb inspectcode $GITHUB_WORKSPACE/Zilon.Core/Zilon.Core.sln --swea --severity=INFO --output=$GITHUB_WORKSPACE/AnalysisResults/ReSharperReport.xml --absolute_paths

      - name: Setup ReSharper to Sonar Converter
        run: dotnet tool install --global dotnet-reqube

      - name: Convert report from ReSharper to SonarQube format
        run: dotnet-reqube --input $GITHUB_WORKSPACE/AnalysisResults/ReSharperReport.xml --output SonarQubeReport.json --directory $GITHUB_WORKSPACE/AnalysisResults

      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          # The key of the SonarQube project
          sonarProjectKey: kreghek_Zilon_Roguelike
          # The name of the SonarQube project
          sonarProjectName:  Zilon Roguelike
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: kreghek
          dotnetBuildArguments: ./Zilon.Core/Zilon.Core.sln
          dotnetDisableTests: true
          sonarBeginArguments: /d:sonar.externalIssuesReportPaths=$GITHUB_WORKSPACE/AnalysisResults/SonarQubeReport.json